@include('layouts.partials.modals.error')
@include('layouts.partials.modals.lang')
@include('layouts.partials.modals.lang_choose', ['available' => strpos($__route->getName(), 'map') === 0 || strpos($__route->getName(), 'ru_map') === 0 ? config('lifestyle.map.available_countries') : null])
@include('layouts.partials.modals.auth')
@include('layouts.partials.modals.subscribe_success') {{-- TODO: CHANGE TESTS MODAL --}}
@include('layouts.partials.modals.video')
@include('layouts.partials.modals.video_uploaded')
@include('layouts.partials.modals.map_photos')

@if (strpos($__route->getName(), 'home') === 0 || strpos($__route->getName(), 'ru_home') === 0)
    @include('layouts.partials.modals.home_subscribe')
    @include('layouts.partials.modals.home_olapic')
@elseif (strpos($__route->getName(), 'map') === 0 || strpos($__route->getName(), 'ru_map') === 0)
    @include('layouts.partials.modals.map_share')
    @include('layouts.partials.modals.map_subscribe')
@elseif (strpos($__route->getName(), 'tests') === 0 || strpos($__route->getName(), 'ru_tests') === 0)
    @include('layouts.partials.modals.tests_error')
@elseif (strpos($__route->getName(), 'account_events') === 0 || strpos($__route->getName(), 'ru_account_events') === 0)
    @include('layouts.partials.modals.account_events_modals')
@elseif (strpos($__route->getName(), 'account_members') === 0 || strpos($__route->getName(), 'ru_account_members') === 0)
    @include('layouts.partials.modals.account_members_modals')
@endif